### ISSUE TITLE
Fix security auth event listeners

### ISSUE THREAD

**Issue by vasiliyfomichev** [vasiliyfomichev/Slack-for-Sitecore#1]
Events are not firing when users log in and out.

**Comment by vlukash** [comment]
More info on this:
security:loggedIn/loggedOut events do not work properly on current Sitecore 8.1 rev. 151207 (Update-1) version. 

I was able to raise these events from custom "loggedin" processor and get security:loggedIn/loggedOut events to work. 
But in this case I see the similar behavior that is described in [Issue #3](https://github.com/vasiliyfomichev/Sitecore-Hackathon-2016/issues/3) - browser hangs after event triggered.

[Posted this issue in community forum](https://community.sitecore.net/developers/f/8/t/2521)

**Comment by vlukash** [comment]
I've opened the Sitecore ticket for this issue. Will keep you posted

**Comment by vlukash** [comment]
From Sitecore support:

////////////////
The described behavior is related to the previously registered bugs (382663, 90553), related to these not used events - this is why they are not triggered.
Instead of the mentioned events, please consider using their analogs:

In the "web.config" file:
<loggedin argsType="Sitecore.Pipelines.LoggedIn.LoggedInArgs">
<logout argsType="Sitecore.Pipelines.Logout.LogoutArgs">
